### PR TITLE
Fix to issue where data[1:0] skips the first byte in UnmarshalBinary

### PR DESCRIPTION
**Pull request by hkumar-rbbn**

### CODE REVIEW

**Comment by free5gc-org** [comment]
@hkumar-rbbn 

Dnn does not include the length, so UnmarshalBinary will skip the first length byte.
What issue did you want to fix?

**Comment by hkumar-rbbn** [comment]
With the current implementation, it skips the first byte in the APP/DNN field itself

Example:

Incoming network instance IE in PDI
        Network Instance : n3-nw
            IE Type: Network Instance (22)
            IE Length: 5
            Network Instance: n3-nw


        Network Instance : dnn.keysight.com

            IE Type: Network Instance (22)

            IE Length: 16

            Network Instance: dnn.keysight.com

Unmarshalled output in the application that handles the received PFCP packet

Network Instance: 3-nw

Network Instance: nn.keysight.com

Fragment returned by parseTLV in tlv package is a map of tag and value. It does not include the length field and hence there is no need to skip the first byte as it results in skipping the first byte of the actual data itself as shown above.
If you look at unmarshall methods of other IEs defined in PFCP stack, it doesn’t skip the first byte.

Let me know if I’m missing something

Regards
Hemanth


From: free5GC ***@***.***>
Sent: Saturday, July 31, 2021 6:11 AM
To: free5gc/util_3gpp ***@***.***>
Cc: Kumar, Hemanth ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [free5gc/util_3gpp] Fix to issue where data[1:0] skips the first byte in UnmarshalBinary (#4)


@hkumar-rbbn<https://clicktime.symantec.com/3CrCMgYW82jwgZiX6eDGSFc6H2?u=https%3A%2F%2Fgithub.com%2Fhkumar-rbbn>

Dnn does not include the length, so UnmarshalBinary will skip the first length byte.
What issue did you want to fix?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3MRDGEpbPJDtWjfk2HZ6pCt6H2?u=https%3A%2F%2Fgithub.com%2Ffree5gc%2Futil_3gpp%2Fpull%2F4%23issuecomment-890324521>, or unsubscribe<https://clicktime.symantec.com/3CPkF5suU4dqnxYM1k1P5mL6H2?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU3TQY5XE45ANXNMPFHOHZLT2PD2RANCNFSM5BITDZ3Q>.

Notice: This e-mail together with any attachments may contain information of Ribbon Communications Inc. and its Affiliates that is confidential and/or proprietary for the sole use of the intended recipient. Any review, disclosure, reliance or distribution by others or forwarding without express permission is strictly prohibited. If you are not the intended recipient, please notify the sender immediately and then delete all copies, including any attachments.

**Comment by turtle11311** [comment]
@hkumar-rbbn 
According to TS 23.003 section 9.1, "Each label is coded as a one octet length field followed by that number of octets coded as 8 bit ASCII characters." So it looks like our implementation is not correct also.

**Comment by free5gc-org** [comment]
@hkumar-rbbn 

As @turtle11311 said, your incoming Network Instance IE encoding in PDI is not correct.

**Comment by hkumar-rbbn** [comment]
Did you get a chance to look at the packet capture I sent earlier?
Both PDI IE Network Instance IE is conformant to standard (29.244) as highlighted in the attached snapshot of pcap(network_instance_ie.jpg). Attaching pcap (test_pfcp_ser.pcap) again for your reference.

Also please find attached pcap from production (pfcp_trace.pcapng) setup. Please take a look at the first Create FAR IE in all the frames that has network instance IE.

"Each label is coded as a one octet length field followed by that number of octets coded as 8 bit ASCII characters"

If you are referring to one octet length field in the above statement from 3GPP spec 23.003, it aligns with length field of network instance IE defined in 29.244

From 29.244 section 8.2.4
"
Network Instance
The Network Instance IE type shall be encoded as shown in Figure 8.2.4-1. It indicates a Network instance.







Bits





Octets

8

7

6

5

4

3

2

1





1 to 2

Type = 22 (decimal)





3 to 4

Length = n





5 to (n+4)

Network Instance



Figure 8.2.4-1: Network Instance
The Network instance field shall be encoded as an OctetString and shall contain an identifier which uniquely identifies a particular Network instance (e.g. PDN instance) in the UP function. It may be encoded as a Domain Name or an Access Point Name (APN) as per clause 9.1 of 3GPP TS 23.003 [2]. In the latter case, the PDN Instance field may contain the APN Network Identifier only or the full APN with both the APN Network Identifier and the APN Operator Identifier as specified in 3GPP TS 23.003 [2] clauses 9.1.1 and 9.1.2.
"

PFCP stack uses util_3gpp.dnn for network instance IE. If 3gpp_dnn expects length field to be encoded within the DNN (first octet), then PFCP stack needs to define a new IE for network instance as per 29.244 instead of referring to util_3gpp DNN. Please confirm if I need to raise a bug on PFCP stack

Regards
Hemanth


From: Kumar, Hemanth
Sent: Saturday, August 7, 2021 11:18 AM
To: free5GC ***@***.******@***.***>; free5gc/util_3gpp ***@***.******@***.***>
Cc: Mention ***@***.******@***.***>
Subject: RE: [EXTERNAL] Re: [free5gc/util_3gpp] Fix to issue where data[1:0] skips the first byte in UnmarshalBinary (#4)

PFA attached capture of Session Establishment Request sent for your reference

**Comment by hkumar-rbbn** [comment]
Hi All,

Could you please provide your input?

Regards
Hemanth


From: Kumar, Hemanth
Sent: Monday, August 16, 2021 4:49 PM
To: free5gc/util_3gpp ***@***.***>; free5gc/util_3gpp ***@***.***>
Subject: FW: [EXTERNAL] Re: [free5gc/util_3gpp] Fix to issue where data[1:0] skips the first byte in UnmarshalBinary (#4)

Did you get a chance to look at the packet capture I sent earlier?
Both PDI IE Network Instance IE is conformant to standard (29.244) as highlighted in the attached snapshot of pcap(network_instance_ie.jpg). Attaching pcap (test_pfcp_ser.pcap) again for your reference.

Also please find attached pcap from production (pfcp_trace.pcapng) setup. Please take a look at the first Create FAR IE in all the frames that has network instance IE.

"Each label is coded as a one octet length field followed by that number of octets coded as 8 bit ASCII characters"

If you are referring to one octet length field in the above statement from 3GPP spec 23.003, it aligns with length field of network instance IE defined in 29.244

From 29.244 section 8.2.4
"
Network Instance
The Network Instance IE type shall be encoded as shown in Figure 8.2.4-1. It indicates a Network instance.







Bits





Octets

8

7

6

5

4

3

2

1





1 to 2

Type = 22 (decimal)





3 to 4

Length = n





5 to (n+4)

Network Instance



Figure 8.2.4-1: Network Instance
The Network instance field shall be encoded as an OctetString and shall contain an identifier which uniquely identifies a particular Network instance (e.g. PDN instance) in the UP function. It may be encoded as a Domain Name or an Access Point Name (APN) as per clause 9.1 of 3GPP TS 23.003 [2]. In the latter case, the PDN Instance field may contain the APN Network Identifier only or the full APN with both the APN Network Identifier and the APN Operator Identifier as specified in 3GPP TS 23.003 [2] clauses 9.1.1 and 9.1.2.
"

PFCP stack uses util_3gpp.dnn for network instance IE. If 3gpp_dnn expects length field to be encoded within the DNN (first octet), then PFCP stack needs to define a new IE for network instance as per 29.244 instead of referring to util_3gpp DNN. Please confirm if I need to raise a bug on PFCP stack

Regards
Hemanth


From: Kumar, Hemanth
Sent: Saturday, August 7, 2021 11:18 AM
To: free5GC ***@***.******@***.***>; free5gc/util_3gpp ***@***.******@***.***>
Cc: Mention ***@***.******@***.***>
Subject: RE: [EXTERNAL] Re: [free5gc/util_3gpp] Fix to issue where data[1:0] skips the first byte in UnmarshalBinary (#4)

PFA attached capture of Session Establishment Request sent for your reference

**Pull request merged**
